server:
  port: 80
spring:
  application:
    name: cloud-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
logging:
  level:
    com.cloudconsumerfeignorder80.service.PaymentFeignService: info
